### ISSUE TITLE
Error After Upgrade

### ISSUE THREAD

**Issue by alfacruxis** [IndigoDomotics/indigo-yamaharx#19]
Today I updated Indigo to v2023.1. Because of that the Yamaha RX v1.0.4 plugin stopped workin since it is not compatible with Python v3+
So, I upgraded the plugin to v2022.0.3 and I get the following error in Indigo log:

  **Upgrading plugin Yamaha RX Receiver to newer version 2022.0.3 (previous version moved to trash)
   Loading plugin "Yamaha RX Receiver 2022.0.3" using API v3.0
   Starting plugin "Yamaha RX Receiver 2022.0.3" (pid 24610)
   Started plugin "Yamaha RX Receiver 2022.0.3"
   Yamaha RX Receiver Error        exception in device_start_comm(Amplificador Living): POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
   Yamaha RX Receiver Error        runConcurrentThread error: 
Traceback (most recent call last):
  File "plugin.py", line 193, in run_concurrent_thread
    self.updateStatus(devId)
  File "plugin.py", line 269, in updateStatus
    root = ClassicReceiver.xmitToReceiver(dev, xml_string)
  File "plugin.py", line 65, in xmitToReceiver
    resp = urllib.request.urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 516, in open
    req = meth(req)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1279, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
   Yamaha RX Receiver Error        plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)**

The plugin keeps trying ever 10 seconds in a non-stop loop.
The plugin configuration menu doesn't show any parameter to change of configure and since the plugin in not loaded, I can neither perform any action on the existing device nor create a new one.

**Comment by autolog** [comment]
I think I may have fixed this?
Please try this pre-release version available here: https://github.com/autolog/indigo-yamaharx/releases/tag/2023.0.4
Let me know how you get on. :)

**Comment by alfacruxis** [comment]
Thanks for the prompt answer.
Actually I realized I had a couple of libraries missing for this an other plugins to work (I recently updated to Ventura OS).
After installing them and tweak some scripts I had, the plugin (v2023.0.3) seems to be loading and working properly.
I was using a version that had a lot of functions, actions and properties for the Yamaha amplifier, that are no longer available.
Seems that plus the missing libraries were the culprits.
I'll prefer to wait for the final release on the v2023.0.4.
Thanks again.

**Comment by damiang1** [comment]
Im having this issue as per my log...

Loading plugin "Yamaha RX Receiver 2022.0.4" using API v3.0
   Starting plugin "Yamaha RX Receiver 2022.0.4" (pid 41070)
   Started plugin "Yamaha RX Receiver 2022.0.4"
   Error (client)                  timeout waiting for plugin response from io.thechad.indigoplugin.yamaharx for request UiGetValues1
   Error (client)                  timeout waiting for plugin response from io.thechad.indigoplugin.yamaharx for request CallPluginFunc
   Error (client)                  runConfigDialog() caught exception: NSInvalidArgumentException -- *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Oct 18, 2023 at 8:40:29 AM
   Yamaha RX Receiver Error        Error in plugin execution startup:

  File "plugin.py", line 151, in startup
  File "plugin.py", line 257, in refresh_receiver_list
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/Plugins/YamahaRX.indigoPlugin/Contents/Server Plugin/rxv/__init__.py", line 19, in find
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/Plugins/YamahaRX.indigoPlugin/Contents/Server Plugin/rxv/ssdp.py", line 68, in discover
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/Plugins/YamahaRX.indigoPlugin/Contents/Server Plugin/rxv/ssdp.py", line 79, in rxv_details
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/requests/api.py", line 75, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/requests/api.py", line 61, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/requests/sessions.py", line 529, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/requests/sessions.py", line 645, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2023.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/requests/adapters.py", line 532, in send
type: HTTPConnectionPool(host='192.168.1.12', port=8008): Read timed out. (read timeout=None)

   Error (client)                  received unexpected packet response UiGetValues1 (waiting for CallPluginFunc)
