### ISSUE TITLE
Error when creating a Yamaha Device

### ISSUE THREAD

**Issue by amann180** [IndigoDomotics/indigo-yamaharx#2]
Hi there,
I have an RX-V473 receiver and am getting an error when I try add a "Yamaha RX Receiver" device with the plugin. After entering the receiver's IP address, I see the following error in Indigo's Event Log"

```
  Yamaha Rx Receiver Debug        updating status...
  Yamaha Rx Receiver Error        Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 6/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 852, in deviceUpdated
  File "plugin.py", line 42, in deviceStartComm
  File "plugin.py", line 59, in updateStatus
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'text'
```

Any Idea what might be going wrong?
Indigo Server 6.0.11
OS X: 10.8.4

Thanks,
-afm

**Comment by indigodomo** [comment]
The 1.0.0 release now supports the RX-Vx73 line of receivers.
